### ISSUE TITLE
raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])

### ISSUE THREAD

**Issue by kabravenkatesh** [kolinger/skyrc-mc3000#3]
My System:
Win10
MC3000 Firmware 1.18 - Updated via the MC3000_Firmware_Update__V1.18.exe
skyrc-mc3000-2.1.0-alfa

I am executing the file mc3000usb.py - works fine 

```
    if task == "save":

        # coms.write(encoder.prepare_slot_settings_read(0))
        data = coms.read()
        slot = encoder.decode_slot_settings(data)

        with open(path, "w") as file:
            file.write(slot.to_json())

        print("successfully saved: %s" % path)

```

I have commented the line for writing because I am not sure how it helps in terms of reading from device to JSON file. 
So, I am getting following error: 

```
raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 10060] Operation timed out
```

Can you please suggest what is the issue here?

**Comment by kabravenkatesh** [comment]
I also wanted to ask whenever I am setting the configuration, 

``` # set the active configuration. 
    coms.device.set_configuration()
```

I am getting following error: 
```raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 10060] Operation timed out```

Have your tried setting the configuration and getting an interface?

**Comment by kolinger** [comment]
The write() part in "save" asks the charger for the data so without the write there is no data to read() - that's why you getting timeout - you didn't ask any question thus you can wait forever and there will be no answer. I'm not sure if you seeing other errors as well but for sure commenting out random lines in code will not help.

**Comment by kabravenkatesh** [comment]
Okay got it. I have one question lingering through my mind: 
1) Are the read and write array identical? I am seeing that they are different: 

```
        coms.write(encoder.prepare_slot_settings_read(0))
        print('Writing this array = {} length = {}'.format(encoder.prepare_slot_settings_read(0), len(encoder.prepare_slot_settings_read(0))))

        data = coms.read()
        print('Read data = {} length = {}'.format(data, len(data)))
```

Output: 
Writing this array = [15, 4, 95, 0, 0, 95, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] length = 64

Read data = array('B', [95, 0, 0, 0, 0, 0, 0, 3, 232, 1, 244, 12, 228, 16, 104, 0, 100, 1, 244, 1, 0, 0, 3, 3, 0, 0, 45, 0, 180, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 232]) length = 64

Did you have any success why: ```coms.device.set_configuration()``` never works on windows 10 PC.

**Comment by kolinger** [comment]
Device is already configured thus second configuration fails with timeout.

**Comment by kolinger** [comment]
The write is question, the read is answer. Method prepare_slot_settings_read(SLOT) prepares question for reading settings, that will tell charger to report settings for specific slot and charger sends it's response. Of course that answer data is not the same data as question, that wouldn't make sense if it was the same.

**Comment by kabravenkatesh** [comment]
Hey thanks a lot for the help. 

I am trying to automate the process of starting the imax charger and foudn the start and stop packets which allow me to start the imax, just curious what would be the series of steps: 
1) Find device (device.open()). 
2) Write host->imax settings. 
3) Start Imax (start packet sequence). 
4) How do I log the data?
5) When to stop the imax? 

Although it is a big ask appreciate any insights or suggestions. Thanks you!

**Comment by kolinger** [comment]
I'm not sure what imax charger you mean thus I can't comment about it specifically and I don't have knowledge about other chargers anyway, if it's similar to MC3000 then this applies.

Yes that's the overall sequence although charger typically stops itself - by terminating the charge when battery is fully charged (or when program completes) or when error occurs. Thus regular sequence is 1) connect 2) write settings 3) start 4) monitor until charger says it's done.

The data logging works the same way as reading settings - you ask charger for status - charger then responds with current progress and that's how you log the progress by periodically asking for status and collecting data points.

If we talk about MC3000 and USB protocol, then great resource is DataExplorer source code:
1) Here you see [command to read status for each slot](https://github.com/gitGNU/gnu_dataexplorer/blob/master/SkyRC/src/gde/device/skyrc/MC3000UsbPort.java#L64)
2) Right bellow is [command to stop charger](https://github.com/gitGNU/gnu_dataexplorer/blob/master/SkyRC/src/gde/device/skyrc/MC3000UsbPort.java#L105) if you want to terminate charger before program completes by itself

DataExplorer source code isn't the simplest and clearest to read but [it's all in there somewhere](https://github.com/gitGNU/gnu_dataexplorer/tree/master/SkyRC/src/gde/device/skyrc).

Bluetooth is somewhat different.

**Comment by kabravenkatesh** [comment]
Hi @kolinger, 

Thanks a lot for the help. I was able to get MC3000 charger protocol information and able to start/stop charger as well. 

The place where I am struggling is logging the battery slot data i.e. voltage, current, time, temperature values. 

I looked at your MC3000ble.py code and saw that you are getting battery charge information through following:
                    `await client.write_gatt_char(self.CHARACTERISTIC_UUID, self.get_channel_request_data(slot))`

where,

`def get_channel_request_data(self, channel_index):
payload = [self.HEADER, self.BATTERY_INFO, channel_index]
while len(payload) < 20:
payload.append(0x00)
self.fill_checksum(payload)
print(payload)
return bytearray(payload)`


I printed the payload for slot 0: [15, 85, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100] (converted to bytes for sending). 

I tried the same request via usb communication as: 
`coms.write(coms.get_channel_request_data(0))

data = coms.read()`        

I am getting following error in coms.read() line: 

`raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])

usb.core.USBTimeoutError: [Errno 10060] Operation timed out`


If the message size is just 20. I get
`usb.core.USBError: [Errno 5] Input/Output Error`

Is there anything I am doing wrong?

**Comment by kolinger** [comment]
Bluetooth has different command format, please refer to DataExplorer where you can see USB commands. If you take Bluetooth payload and send it over USB then it's invalid message and thus charger will ignore it and thus read will end as timeout.

**Comment by kolinger** [comment]
Closing since it's not related to this project.
